source_set("tab_tree_adapter") {
  sources = [ "tab_tree_adapter.cc", "tab_tree_adapter.h" ]
  public_deps = [
    "//base",
    "//ui/base",
    "//ui/base/clipboard",
    "//ui/views",
    "//uw/browser/tab_organization",
  ]
  deps = [
    "//chrome:strings",
    "//chrome/browser:browser_public_dependencies",
    "//chrome/browser/ui/browser_window",
    "//chrome/browser/ui/views/frame",
    "//chrome/browser/ui/views/tabs/common:common",
    "//ui/accessibility:ax_base",
    "//ui/base/dragdrop",
    "//ui/base/dragdrop:types",
    "//ui/compositor",
    "//ui/gfx/geometry",
  ]
}
